version: "3.8"

services:
  datacollector:
    container_name: data_collector
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    networks:
      - datacollector
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: timescale/timescaledb:latest-pg14
    environment:
      - PGUSER=root
      - POSTGRES_DB=datacollectordb
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
    networks:
      - datacollector
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "quarkus", "-u", "root"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  datacollector:
    name: datacollector