version: "3.8"

services:
  delayedservice:
    image: busybox
    command: >
      sh -c "echo 'Delaying startup...'; sleep 60; echo 'Delay complete.'"
  datacollector:
    container_name: data_collector
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - database:
        condition: service_healthy
      delayedservice:
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/quarkus
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=quarkus
      - MP_MESSAGING_INCOMING_SIMULATOR=85.215.60.151
      - MP_MESSAGING_INCOMING_SIMULATOR_PORT=1884
  database:
    container_name: database
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_DB=quarkus
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - PGUSER=quarkus
      - POSTGRES_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - back-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "quarkus", "-u", "quarkus"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  front-tier:
    name: front-tier
  back-tier:
    name: back-tier